# Height_Adjustment.action
# Action definition for adjusting the height of Unitree Go2


bool passable
float32 required_height_adjustment
---
# Result: Was the navigation successful?
bool success
string message
---
# Feedback: Current progress
string status